version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test-py-27-django-1-8:
    docker:
      - image: cimg/python:3.9.0
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pip install tox && tox -e py27-django1.8
  build-and-test-py-27-django-1-11:
    docker:
      - image: cimg/python:3.9.0
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pip install tox && tox -e py27-django1.11
  build-and-test-py-39-django-2-1:
    docker:
      - image: cimg/python:3.9.0
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            B2C_PHONE_NUMBER=254722000000 pip install tox && tox -e py27-django1.11
workflows:
  sample:
    jobs:
      - build-and-test-py-27-django-1-8
      - build-and-test-py-27-django-1-11
      - build-and-test-py-39-django-2-1
